version: '3.8'
services:
  db:
    image: test_postgres
    container_name: testBase
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - "C:/DbVolumes:/var/lib/postgresql/data"
